<?php

/**
 * @file
 * This module emails exceptions to admin users.
 */

/**
 * Implements hook_mail().
 */
function exception_mailer_mail($key, &$message, $params) {
  if ($key === "notify_exception") {
    $body =
    t('An exception has occurred.

    Site name: @site

    Date: @date

    User: @user

    Location: @location

    Referrer: @referrer

    Link: @link

    Type: @type

    Severity: @severity

    Exception: @exception

    Exception message: @message

    Hostname: @hostname

    Thank you.', [
      '@site' => $params['site'],
      '@date' => $params['date'],
      '@user' => $params['user'],
      '@location' => $params['location'],
      '@referrer' => $params['referrer'],
      '@link' => $params['link'],
      '@type' => $params['type'],
      '@severity' => $params['severity'],
      '@exception' => $params['exception'],
      '@message' => $params['message'],
      '@hostname' => $params['hostname'],
      ]);
    $message['subject'] = t('An exception/error occurred (@exception @error)', ['@exception' => $params['exception'], '@error' => $params['severity']]);
    $message['body'][] = $body;
  }
}
