<?php

/**
 * @file
 * This module emails exceptions to admin users.
 */

/**
 * Implements hook_mail().
 */
function exception_mailer_mail($key, &$message, $params) {
  if ($key === 'notify_exception') {
    $body =
    t('An @exception_error has occurred.

    Site name: @site
    Date: @date
    User: @user
    Location: @location
    Referrer: @referrer
    Link: @link
    Type: @type
    Severity: @severity
    Hostname: @hostname

    Exception: @exception

    Exception message: @message

    Thank you.', [
      '@exception_error' => !$params['severity'] ? 'exception' : 'error',
      '@site' => $params['site'],
      '@date' => \Drupal::service('date.formatter')->format($params['timestamp'], 'short'),
      '@user' => $params['user'],
      '@location' => $params['location'],
      '@referrer' => $params['referrer'],
      '@link' => $params['link'],
      '@type' => $params['type'],
      '@severity' => $params['severity'],
      '@exception' => $params['exception'],
      '@message' => $params['message'],
      '@hostname' => $params['hostname'],
    ]);

    if ($params['exception']) {
      $message['subject'] = t('An exception occurred (@exception)', ['@exception' => $params['exception']]);
    }
    else {
      $message['subject'] = t('An error occurred (@severity)', ['@severity' => $params['severity']]);
    }

    $message['body'][] = $body;
  }
}
