exception_mailer.settings:
  type: config_object
  label: 'Exception mailer settings'
  mapping:
    level_type:
      type: sequence
      label: 'Level types for errors'
      sequence:
          type: string
